### ISSUE TITLE
Support specify aliases when using local repl

### ISSUE THREAD

**Issue by gerdint** [afucher/clojure-repl-intellij#44]
I have a full-stack deps.edn+shadow-cljs project (with shadow-cljs deps handled using a `cljs` alias in deps.edn). When I start configure and add Clojure REPL of "Local" type I would expect it to start the Clojure CLI with some configurable aliases. Instead is executes `npx shadow-cljs server`, while not entirely unhelpful, is somewhat surprising.

I would be good with some docs on what is actually on offer here. Does it support deps.edn, Leiningen or what?

I'm on macOS 11.7.10 and IntelliJ IDEA 2023.3.4 (Ultimate Edition).

**Comment by ericdallo** [comment]
@gerdint we support all major build deps, but we don't support specify aliases yet, it should not be hard, I can take a look soon at this.
