### ISSUE TITLE
Support running tests through REPL

### ISSUE THREAD

**Issue by devurandom** [afucher/clojure-repl-intellij#46]
It would be great if the plugin would support running `clojure.test` tests (the whole namespace or individual `deftest`s) through the REPL.

Succeeding tests could be marked in the editor. See https://cursive-ide.com/userguide/testing.html for how this could look like.

Cursive  supports this, but sadly not yet as a default mode, cf. https://github.com/cursive-ide/cursive/issues/2770.

**Comment by ericdallo** [comment]
This is our top priority right now! we were just missing a issue to track that, thanks

**Comment by devurandom** [comment]
> @devurandom If you wanna give it a try :) #49

Thanks for working on this!

I tried installing the file you attached to https://github.com/afucher/clojure-repl-intellij/pull/49#issuecomment-2015946711, but did not succeed. How do I run a test? I tried right clicking the `deftest` symbol and the symbol of the test (i.e. `the-test` in `(deftest the-test ,,,)`), but could not find an option to run the test. This does not change when I open an nREPL console window.

Unrelated (maybe?) things I noticed when trying:
* The IntelliJ `java` process no longer exits by itself when trying to restart IntelliJ. I have to send `SIGKILL` (`kill -9 ...`) to terminate it and then start IntelliJ again.
* The REPL has a dark background with black text. Hardly legible.
* The Clojure REPL plugin I installed from https://github.com/afucher/clojure-repl-intellij/pull/49#issuecomment-2015946711 has version number `0.1.6` and not `0.1.6-snapshot` or similar. Not sure whether I am using the right version.
* When I create a remote REPL / nREPL run configuration and select "read from repl file", apply, ok, and then go back and edit the run configuration, the connection type is set to "manual" instead of "read from repl file".

**Comment by ericdallo** [comment]
@devurandom it's exactly how it run a test in all other editors, via a command `run test`, I added docs [here](https://github.com/afucher/clojure-repl-intellij/pull/49/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R47-R48), maybe we should add a option via the context menu on click or something

**Comment by ericdallo** [comment]
> The IntelliJ java process no longer exits by itself when trying to restart IntelliJ. I have to send SIGKILL (kill -9 ...) to terminate it and then start IntelliJ again.

Probably not related with this PR, probably something else

> The REPL has a dark background with black text. Hardly legible.

There is a existing issue to customize repl colors.

> The Clojure REPL plugin I installed

that's expected since it's a dev build, we didn't customize that yet, but I don't see any problem or priority to do this now.

> hen I create a remote REPL / nREPL run configuration and select "read from repl file", apply, ok, and then go back and edit the run configuration, the connection type is set to "manual" instead of "read from repl file".

I guess it's a known issue @afucher it's working on.

**Comment by devurandom** [comment]
> @devurandom it's exactly how it run a test in all other editors, via a command `run test`, I added docs [here](https://github.com/afucher/clojure-repl-intellij/pull/49/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R47-R48), maybe we should add a option via the context menu on click or something

This is how it looks like in Cursive: 
![image](https://github.com/afucher/clojure-repl-intellij/assets/63082/1b939967-fd3b-4fd4-9fee-0533eac3189b)

**Comment by ericdallo** [comment]
Thanks, I think we can add that too

**Comment by ericdallo** [comment]
Done on v3 [here](https://github.com/afucher/clojure-repl-intellij/pull/49#issuecomment-2018991495)!
