### ISSUE TITLE
LSP is stuck on "Initializing" step

### ISSUE THREAD

**Issue by lucasfcoelho1** [afucher/clojure-repl-intellij#50]
**Describe the bug**
I've installed both `Clojure LSP 2.3.1` and `Clojure REPL 0.1.6`.
I was able to start a REPL, but cannot use the LSP. It is stuck on the `LSP: Initializing` step and I could not navigate through files or functions.

**Screenshots**
![image](https://github.com/afucher/clojure-repl-intellij/assets/11428605/6e4701fc-4619-40a2-89ab-e20927bf8d92)

**Environment (please complete the following information):**
 - IntelliJ Version: IntelliJ IDEA 2023.3.4 (Community Edition)
Build #IC-233.14475.28, built on February 13, 2024
Runtime version: 17.0.10+1-b1087.17 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 13.6.5
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.clojure-repl (0.1.6)
  manjaro.mpb (1.9)
  com.github.catppuccin.jetbrains_icons (1.4.0)
  com.github.clojure-lsp (2.3.1)
  izhangzhihao.rainbow.brackets (2024.2.2-233)
  com.github.copilot (1.5.1.5285)
  com.mallowigi (94.1.0)
Kotlin: 233.14475.28-IJ

 - OS: MacOS Ventura 13.6.5 (22G621)

**Additional context**
Before install I removed the Cursive plugin to avoid any conflicts, but no success.

**Comment by afucher** [comment]
Hey @lucasfcoelho1 , seems this is an issue with LSP please open in the lsp plugin project: https://github.com/clojure-lsp/clojure-lsp-intellij
