### ISSUE TITLE
Printing in test fails test

### ISSUE THREAD

**Issue by andreformento** [afucher/clojure-repl-intellij#62]
**Describe the bug**
Any println throw an error.

**To Reproduce**
1. Put a println on your production code: `(println "my text here")`
3. Load the NS and run your test
4. See error: `java.lang.IllegalArgumentException: No implementation of method: :send of protocol: #'nrepl.transport/Transport found for class: nil`

**Expected behavior**
The println should work! ~If not, I cannot work~ :trollface: 

**Screenshots**
![image](https://github.com/afucher/clojure-repl-intellij/assets/5116933/0c2093be-142b-4816-977b-5fca46197d13)
![image](https://github.com/afucher/clojure-repl-intellij/assets/5116933/96194564-7eaf-4bb4-ba20-839221f0ad53)
![image](https://github.com/afucher/clojure-repl-intellij/assets/5116933/ec9c2837-2a3f-4f03-b5d7-0b366b4d5c99)

**Environment (please complete the following information):**

 - IntelliJ Version:
```
IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  scala.erase.compiler.process.jdk.once=false
Non-Bundled Plugins:
  com.github.clojure-repl (1.0.3)
  com.github.clojure-lsp (2.3.8)
  com.jetbrains.space (241.14494.150)
  com.github.copilot (1.5.2.5345)
  org.intellij.scala (2024.1.15)
Kotlin: 241.14494.240-IJ
```
 - OS:
![image](https://github.com/afucher/clojure-repl-intellij/assets/5116933/22a4fea6-2af4-4fc3-8d12-e3cbeeff7f43)

**Additional context**
`#nu/tap` doesn't work either

**Comment by ericdallo** [comment]
Thanks for the report, I can repro the problem! I'll focus on that

**Comment by ericdallo** [comment]
A little bit related issue: https://github.com/afucher/clojure-repl-intellij/issues/65
