### ISSUE TITLE
Improve printing in REPL

### ISSUE THREAD

**Issue by andreformento** [afucher/clojure-repl-intellij#70]
**Describe the bug**
The printer is working, but the text is a little fuzzy when there is a color. Can you improve this?

**To Reproduce**
1. Just put a println with a color
2. The text printed don't "convert the color"

**Expected behavior**
Print colored on the REPL

**Screenshots**

![image](https://github.com/afucher/clojure-repl-intellij/assets/5116933/77fa7405-9917-48b9-aa42-b507e39799f2)

**Environment (please complete the following information):**
 - IntelliJ Version: [e.g. IDEA 2023.2.5 (Community Edition)]
 - OS [e.g. MacOS, Windows, Linux]

**Additional context**

**Comment by ericdallo** [comment]
That happens because our console doesn't support ansi chars yet, what we did for test summary was to remove those chars until we support those custom colors, we should do the same on console

**Comment by ericdallo** [comment]
Fixed on 1.1.2
![image](https://github.com/afucher/clojure-repl-intellij/assets/7820865/9d355295-302b-4419-aabb-a16af2a4442c)

for now we are removing the ansii chars, in the future we may support present the colors
