### ISSUE TITLE
Feature Request: Icon trash to clear REPL History

### ISSUE THREAD

**Issue by mefryar** [afucher/clojure-repl-intellij#77]
**Describe the feature requested**
This is a feature request rather than a bug report. It would be nice to be able to clear the REPL window. Because error messages can be quite long, when iterating on tests, it helps me to clear the REPL window after each test so I can easily navigate between the beginning of the error message and the end of the error message.

**Expected behavior**
A trash can icon exists, as in Cursive.

**Screenshots**
clojure-repl-intellij
<img width="1792" alt="image" src="https://github.com/afucher/clojure-repl-intellij/assets/21371788/2986f3a1-1313-4a60-b046-448555282b33">

Cursive
<img width="1792" alt="image" src="https://github.com/afucher/clojure-repl-intellij/assets/21371788/480913a4-49e5-405d-9bee-e795f48a402b">

**Environment (please complete the following information):**
IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 14.4.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Metal Rendering is ON
Registry:
  debugger.new.tool.window.layout=true
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.clojure-repl (1.3.1)
  com.github.clojure-lsp (2.4.5)
  IdeaVIM (2.11.0)
  izhangzhihao.rainbow.brackets (2024.2.3-241)
  com.jetbrains.packagesearch.intellij-plugin (241.0.9)
  com.github.copilot (1.5.3.5510)
Kotlin: 241.14494.240-IJ

**Comment by afucher** [comment]
Hey @mefryar, thanks for bringing this!
We already have a command to clear the REPL `ctrl + l`, but I think that is not documented 🫣 sorry

But I will keep this issue open to implement the trash icon.

**Comment by mefryar** [comment]
Thanks for the fast response @afucher! I tried `ctrl + l`, but it didn't work as expected for me.

**Comment by afucher** [comment]
Hey @mefryar , you need to have the focus on the REPL window. For now, we do not have a global shortcut to clear the REPL.
Have you tried `ctrl+l` with the cursos on the REPL window ? If no, can you please try it again?

**Comment by mefryar** [comment]
I realized that I had a keyboard shortcut enabled to map `⌃L` to simulate a right arrow keystroke. Now that I've disabled that `⌃L` works to clear the REPL window!

**Comment by ericdallo** [comment]
BTW @afucher I think we can have a action for that, so we can clear the reply history from any window

**Comment by ericdallo** [comment]
Closing this as we now have a Clear REPL output shortcut (`alt/opt + shift + R` `alt/opt + shift + C`)
