### ISSUE TITLE
Create IntelliJ action to clear REPL

### ISSUE THREAD

**Issue by afucher** [afucher/clojure-repl-intellij#78]
Today the plugin just allow clear the REPL when the focus is in the REPL window.
The idea is to have an action in IntelliJ to allow user to clear the REPL from any place inside IntelliJ

Ref: #77

**Comment by ericdallo** [comment]
Fixed by https://github.com/afucher/clojure-repl-intellij/commit/23683fb55ea1db87866559031b840e607b6e1105
