### ISSUE TITLE
Add load all project files action with shortcut

### ISSUE THREAD

**Issue by yullidias** [afucher/clojure-repl-intellij#80]
**Describe the bug**
Today we need to load the modified files one by one. Could you please implement the feature to update all files using a shortcut? Also, would be good to have another shortcut to load just the modified files

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - IntelliJ Version: [e.g. IDEA 2023.2.5 (Community Edition)]
 - OS [e.g. MacOS, Windows, Linux]

**Additional context**

**Comment by ericdallo** [comment]
I think we can have a separated issue for the modified ones as I'm now sure how we should support but I have a feeling it should not be hard using cider-nrepl

**Comment by yullidias** [comment]
I created other issue for the modified files
https://github.com/afucher/clojure-repl-intellij/issues/81
