### ISSUE TITLE
Background Color is hardcoded, which leads to low contrast in light mode

### ISSUE THREAD

**Issue by ngrandas** [afucher/clojure-repl-intellij#82]
**Describe the bug**
The background is currently hardcoded, meaning on light mode the background is dark

**To Reproduce**
1. Run something on the REPL

**Expected behavior**
A clear and concise description of what you expected to happen. I expected the background to be light

**Screenshots**
<img width="1709" alt="Screenshot 2024-07-10 at 9 24 16 AM" src="https://github.com/afucher/clojure-repl-intellij/assets/95664513/6b51cb1a-a69c-4979-8b48-dcc38118bd39">

**Environment (please complete the following information):**
 - IntelliJ Version: 2024.1.4
 - OS MacOs

**Additional context**

**Comment by ericdallo** [comment]
We are using [JBColor/background](https://github.com/afucher/clojure-repl-intellij/blob/a4b9cc33660d7e808a4abd9786cba79852809c1f/src/main/clojure/com/github/clojure_repl/intellij/ui/color.clj#L13), which is expected to be theme friendly, it works for me, not sure why happens to you, are you sure you have your plugin updated?

![image](https://github.com/user-attachments/assets/9039476f-2ab9-4cf6-8524-d91c841dfda4)

**Comment by afucher** [comment]
It was already fixed by @ngrandas ,just forgot to close this issue
