### ISSUE TITLE
Can't execue lein on windows

### ISSUE THREAD

**Issue by DavidAlphaFox** [afucher/clojure-repl-intellij#85]
**Describe the bug**
I put the lein.bat under "C:/Users/david/bin" and add the path in enviroments.
But the plug in can't execute it. And I get 

```
Cannot run program "lein" (in directory "C:\Users\david\source\stock"): CreateProcess error=2
```

**Environment (please complete the following information):**

IntelliJ IDEA 2024.1.4 (Ultimate Edition)
Build #IU-241.18034.62, built on June 21, 2024
Licensed to Tianpo Gao
You have a perpetual fallback license for this version.
Subscription is active until June 13, 2025.
Runtime version: 17.0.11+1-b1207.24 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.clojure-repl (1.4.1)
  com.github.clojure-lsp (2.6.0)
Kotlin: 241.18034.62-IJ

**Comment by afucher** [comment]
Hello @DavidAlphaFox,
Can you please add more information about the error? When it happens? Do it have the stacktrace?

**Comment by ericdallo** [comment]
hum, maybe for windows we should run it as `lein.bat` 🤔

**Comment by ericdallo** [comment]
@DavidAlphaFox could you confirm that if you run `lein.bat repl` in your terminal it works?

**Comment by ericdallo** [comment]
@DavidAlphaFox I made some adjustments that I know are required for windows, could you install this plugin please?

I think it might fix #84 as well

[clojure-repl-1.4.2.zip](https://github.com/user-attachments/files/16570892/clojure-repl-1.4.2.zip)

**Comment by ericdallo** [comment]
I'm pretty sure it fixes windows support, LMK otherwise

**Comment by DavidAlphaFox** [comment]
@ericdallo 

I tried the 1.5.0 on my windows machine. It still gives me the same error.
By the way I use Windows Home version.

```
IntelliJ IDEA 2024.1.6 (Ultimate Edition)
Build #IU-241.19072.14, built on August 8, 2024
Licensed to Tianpo Gao
You have a perpetual fallback license for this version.
Subscription is active until June 13, 2025.
Runtime version: 17.0.11+1-b1207.30 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 8
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  com.github.clojure-repl (1.5.0)
  com.github.clojure-lsp (2.6.1)
Kotlin: 241.19072.14-IJ
```
