### ISSUE TITLE
Use arrow-up to re-run the last expression

### ISSUE THREAD

**Issue by nicollecnunes** [afucher/clojure-repl-intellij#91]
**Describe the bug**
As someone who just migrated from Cursive REPL, at first I missed the shortcut to use ⬆️ to re-run the last test I sent.

**To Reproduce**
1. Run (example-test)
2. Tap ⬆️ on the keyboard
3. The (example-test) does not appear again

**Expected behavior**
1. Run (example-test)
2. Tap ⬆️ on the keyboard
3. The (example-test) appears again on REPL so that you just need to tap enter to run it again

**Environment (please complete the following information):**
 - IntelliJ IDEA 2024.2.4 (Community Edition)
 - MacOS

**Comment by juusechec** [comment]
👋 Hi, I want to add that I also miss an easy way of re-execute the last executed test. This is useful when you are making changes in files that are not the test. 

💯 Thanks for the plugin @afucher @ericdallo !

**Comment by ericdallo** [comment]
@nicollecnunes this is already supported via `Ctrl` + `up/down`, but there is a minor bug I fixed on master available on next release.

**Comment by ericdallo** [comment]
@juusechec The support to run last test is another issue not related with this one, but since this one was already implement I'll rename this one to this feature
